#frontend:
#  image: stegruslan/latest
#
#
#  container_name: front
#  ports:
#    - "80:80"
#  restart: unless-stopped
#  networks:
#    - app
#
#backend:
#  image: stegruslan/latest
#  container_name: backend
#
#
#  env_file:
#    - .env
#  networks:
#    - app
#  volumes:
#    - ./media_files:/opt/app/media_files
#
#networks:
#  app:
#    external: true



services:
  frontend:
    image: stegruslan/fotogram-frontend:latest
    container_name: front
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app

  backend:
    image: stegruslan/fotogram-backend:latest
    container_name: backend
    env_file:
      - .env
    networks:
      - app
    volumes:
      - ./media_files:/opt/app/media_files

networks:
  app:
    external: true
