
services:
  migrations:
    image: stegruslan/fotogram-backend:latest
    container_name: migrations
    env_file:
      - .env
    command: alembic upgrade head
    networks:
      - app
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    volumes:
      - ./database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app



  frontend:
    image: stegruslan/fotogram-frontend:latest
    container_name: front
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app

  backend:
    image: stegruslan/fotogram-backend:latest
    container_name: backend
    env_file:
      - .env
    networks:
      - app
    volumes:
      - ./media_files:/opt/app/media_files

networks:
  app:
    external: true

